2020-04-13 11:23:52,835 INFO: Microblog startup [in /home/boadzie/Documents/Dev_Master/Flask_projects/microblog/app/__init__.py:45]
2020-04-13 11:31:31,073 INFO: Microblog startup [in /home/boadzie/Documents/Dev_Master/Flask_projects/microblog/app/__init__.py:45]
2020-04-13 11:31:38,593 ERROR: Exception on /edit_profile [POST] [in /home/boadzie/anaconda3/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/boadzie/Documents/Dev_Master/Flask_projects/microblog/app/routes.py", line 79, in edit_profile
    if form.validate_on_submit():
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/flask_wtf/form.py", line 100, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/wtforms/fields/core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/wtforms/fields/core.py", line 226, in _run_validation_chain
    validator(form, self)
  File "/home/boadzie/Documents/Dev_Master/Flask_projects/microblog/app/forms.py", line 42, in validate_username
    user = User.query.filter_by(email=email.data).first()
NameError: name 'email' is not defined
2020-04-13 11:31:47,808 ERROR: Exception on /edit_profile [POST] [in /home/boadzie/anaconda3/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/boadzie/Documents/Dev_Master/Flask_projects/microblog/app/routes.py", line 79, in edit_profile
    if form.validate_on_submit():
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/flask_wtf/form.py", line 100, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/wtforms/fields/core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/boadzie/anaconda3/lib/python3.7/site-packages/wtforms/fields/core.py", line 226, in _run_validation_chain
    validator(form, self)
  File "/home/boadzie/Documents/Dev_Master/Flask_projects/microblog/app/forms.py", line 42, in validate_username
    user = User.query.filter_by(email=email.data).first()
NameError: name 'email' is not defined
2020-04-13 11:33:22,834 INFO: Microblog startup [in /home/boadzie/Documents/Dev_Master/Flask_projects/microblog/app/__init__.py:45]
